// update this to pull dynamic data

export default defineEventHandler((event) => {
  return [
    { set: "LRW", name: "Ajani Goldmane" },
    { set: "AER", name: "Ajani Unyielding" },
    { set: "M19", name: "Ajani, Adversary of Tyrants" },
    { set: "JOU", name: "Ajani, Mentor of Heroes" },
    { set: "MH3", name: "Ajani, Nacatl Pariah" },
    { set: "DMU", name: "Ajani, Sleeper Agent" },
    { set: "M20", name: "Ajani, Strength of the Pride" },
    { set: "M19", name: "Ajani, Wise Counselor" },
    { set: "C18", name: "Aminatou, the Fateshifter" },
    { set: "RIX", name: "Angrath, Minotaur Pirate" },
    { set: "RIX", name: "Angrath, the Flame-Chained" },
    { set: "MOM", name: "Archangel Elspeth" },
    { set: "MID", name: "Arlinn, the Pack's Hope" },
    { set: "THB", name: "Ashiok, Nightmare Muse" },
    { set: "THB", name: "Ashiok, Sculptor of Fears" },
    { set: "WOE", name: "Ashiok, Wicked Manipulator" },
    { set: "UND", name: "B.O.B. Bevy of Beebles" },
    { set: "M21", name: "Basri Ket" },
    { set: "THB", name: "Calix, Destiny's Hand" },
    { set: "LRW", name: "Chandra Nalaar" },
    { set: "M20", name: "Chandra, Acolyte of Flame" },
    { set: "M20", name: "Chandra, Awakened Inferno" },
    { set: "DOM", name: "Chandra, Bold Pyromance" },
    { set: "VOW", name: "Chandra, Dressed to Kill" },
    { set: "M21", name: "Chandra, Heart of Fire" },
    { set: "MOM", name: "Chandra, Hope's Beacon" },
    { set: "KAL", name: "Chandra, Pyrogenius" },
    { set: "KAL", name: "Chandra, Torch of Defiance" },
    { set: "UNF", name: "Comet, Stellar Pup" },
    { set: "CMM", name: "Commodore Guff" },
    { set: "MH2", name: "Dakkon, Shadow Slayer" },
    { set: "J21", name: "Davriel, Soul Broker" },
    { set: "DMC", name: "Dihada, Binder of Wills" },
    { set: "RNA", name: "Domri, Chaos Bringer" },
    { set: "RNA", name: "Dovin, Architect of Law" },
    { set: "RNA", name: "Dovin, Grand Arbiter" },
    { set: "AFR", name: "Ellywick Tumblestrum" },
    { set: "CLB", name: "Elminster" },
    { set: "SNC", name: "Elspeth Resplendent" },
    { set: "ALA", name: "Elspeth, Knight-Errant" },
    { set: "THB", name: "Elspeth, Sun's Nemesis" },
    { set: "THB", name: "Elspeth, Undaunted Hero" },
    { set: "C18", name: "Estrid, the Masked" },
    { set: "J21", name: "Freyalise, Skyshroud Partisan" },
    { set: "LRW", name: "Garruk Wildspeaker" },
    { set: "M12", name: "Garruk, Primal Hunter" },
    { set: "A22", name: "Garruk, Wrath of the Wilds" },
    { set: "MH2", name: "Geyadrone Dihada" },
    { set: "WAR", name: "Gideon Blackblade" },
    { set: "ROE", name: "Gideon Jura" },
    { set: "AKH", name: "Gideon of the Trials" },
    { set: "BFZ", name: "Gideon, Ally of Zendikar" },
    { set: "AKH", name: "Gideon, Martial Paragon" },
    { set: "WAR", name: "Gideon, the Oathsworn" },
    { set: "MH2", name: "Grist, the Hunger Tide" },
    { set: "XLN", name: "Huatli, Dinosaur Knight" },
    { set: "RIX", name: "Huatli, Radiant Champion" },
    { set: "XLN", name: "Huatli, Warrior Poet" },
    { set: "OTJ", name: "Jace Reawakened" },
    { set: "WAR", name: "Jace, Arcane Strategist" },
    { set: "XLN", name: "Jace, Cunning Castaway" },
    { set: "XLN", name: "Jace, Ingenious Mind-Mage" },
    { set: "ZNR", name: "Jace, Mirror Mage" },
    { set: "WAR", name: "Jace, Wielder of Mysteries" },
    { set: "M15", name: "Jace, the Living Guildpact" },
    { set: "ONE", name: "Jace, the Perfected Mind" },
    { set: "DOM", name: "Jaya Ballard" },
    { set: "DMU", name: "Jaya, Fiery Negotiator" },
    { set: "WAR", name: "Jaya, Venerated Firemage" },
    { set: "CMR", name: "Jeska, Thrice Reborn" },
    { set: "GS1", name: "Jiang Yanggu" },
    { set: "NEO", name: "Kaito Shizuki" },
    { set: "DMU", name: "Karn, Living Legacy" },
    { set: "DOM", name: "Karn, Scion of Urza" },
    { set: "WAR", name: "Karn, the Great Creator" },
    { set: "STX", name: "Kasmina, Enigma Sage" },
    { set: "KHM", name: "Kaya the Inexorable" },
    { set: "VOW", name: "Kaya, Geist Hunter" },
    { set: "RNA", name: "Kaya, Orzhov Usurper" },
    { set: "MKM", name: "Kaya, Spirits' Justice" },
    { set: "J21", name: "Kiora, the Tide's Fury" },
    { set: "SOM", name: "Koth of the Hammer" },
    { set: "ONE", name: "Koth, Fire of Resistance" },
    { set: "LRW", name: "Liliana Vess" },
    { set: "AKH", name: "Liliana, Death Wielder" },
    { set: "AKH", name: "Liliana, Death's Majesty" },
    { set: "WAR", name: "Liliana, Dreadhorde General" },
    { set: "M19", name: "Liliana, Untouched by Death" },
    { set: "M21", name: "Liliana, Waker of the Dead" },
    { set: "BFZ", name: "Liliana, the Last Hope" },
    { set: "M19", name: "Liliana, the Necromancer" },
    { set: "AFR", name: "Lolth, Spider Queen" },
    { set: "C18", name: "Lord Windgrace" },
    { set: "ONE", name: "Lukka, Bound to Ruin" },
    { set: "IKO", name: "Lukka, Coppercoat Outcast" },
    { set: "STX", name: "Mila, Crafty Companion" },
    { set: "AFR", name: "Mordenkainen" },
    { set: "GS1", name: "Mu Yanling" },
    { set: "M20", name: "Mu Yanling, Sky Dancer" },
    { set: "ZNR", name: "Nahiri, Heir of the Ancients" },
    { set: "IKO", name: "Narset of the Ancient Way" },
    { set: "WAR", name: "Nicol Bolas, Dragon-God" },
    { set: "HOU", name: "Nicol Bolas, God-Pharaoh" },
    { set: "HOU", name: "Nicol Bolas, the Deceiver" },
    { set: "M19", name: "Nicol Bolas, the Ravager" },
    { set: "ZNR", name: "Nissa of Shadowed Boughs" },
    { set: "ONE", name: "Nissa, Ascended Animist" },
    { set: "HOU", name: "Nissa, Genesis Mage" },
    { set: "KAL", name: "Nissa, Nature's Artisan" },
    { set: "AKH", name: "Nissa, Steward of Elements" },
    { set: "WAR", name: "Nissa, Who Shakes the World" },
    { set: "SNC", name: "Ob Nixilis, the Adversary" },
    { set: "ELD", name: "Oko, Thief of Crowns" },
    { set: "OTJ", name: "Oko, the Ringleader" },
    { set: "STX", name: "Professor Onyx" },
    { set: "LCI", name: "Quintorius Kand" },
    { set: "GRN", name: "Ral, Izzet Viceroy" },
    { set: "WAR", name: "Ral, Storm Conduit" },
    { set: "BBD", name: "Rowan Kenrith" },
    { set: "STX", name: "Rowan, Scholar of Sparks" },
    { set: "BRO", name: "Saheeli, Filigree Master" },
    { set: "HOU", name: "Samut, the Tested" },
    { set: "M19", name: "Sarkhan, Dragonsoul" },
    { set: "M19", name: "Sarkhan, Fireblood" },
    { set: "J21", name: "Sarkhan, Wanderer to Shiv" },
    { set: "MH2", name: "Serra the Benevolent" },
    { set: "DMC", name: "Sivitri, Dragon Master" },
    { set: "ZEN", name: "Sorin Markov" },
    { set: "VOW", name: "Sorin the Mirthless" },
    { set: "M20", name: "Sorin, Imperious Bloodlord" },
    { set: "WAR", name: "Sorin, Vengeful Bloodlord" },
    { set: "NEO", name: "Tamiyo, Compleated Sage" },
    { set: "CLB", name: "Tasha, the Witch Queen" },
    { set: "DOM", name: "Tefari, Hero of Dominaria" },
    { set: "DOM", name: "Tefari, Timebender" },
    { set: "MOM", name: "Teferi Akosa of Zhalfir" },
    { set: "M21", name: "Teferi, Master of Time" },
    { set: "M21", name: "Teferi, Master of Time" },
    { set: "BRO", name: "Teferi, Temporal Pilgrim" },
    { set: "WAR", name: "Teferi, Time Raveler" },
    { set: "MID", name: "Teferi, Who Slows the Sunset" },
    { set: "CMR", name: "Tevesh Szat, Doom of Fools" },
    { set: "J21", name: "Teyo, Aegis Adept" },
    { set: "ALA", name: "Tezzeret the Seeker" },
    { set: "M19", name: "Tezzeret, Artifice Master" },
    { set: "NEO", name: "Tezzeret, Betrayer of Flesh" },
    { set: "M19", name: "Tezzeret, Cruel Machinist" },
    { set: "AER", name: "Tezzeret, Master of Metal" },
    { set: "WAR", name: "Tezzeret, Master of the Bridge" },
    { set: "ONE", name: "The Eternal Wanderer" },
    { set: "WAR", name: "The Wanderer" },
    { set: "NEO", name: "The Wandering Emperor" },
    { set: "A22", name: "Tibalt, Wicked Tormentor" },
    { set: "KHM", name: "Tyvar Kell" },
    { set: "ONE", name: "Tyvar, Jubilant Brawler" },
    { set: "WAR", name: "Ugin, the Ineffable" },
    { set: "UST", name: "Urza, Academy Headmaster" },
    { set: "BRO", name: "Urza, Planeswalker" },
    { set: "KHM", name: "Valki, God of Lies" },
    { set: "SOM", name: "Venser, the Sojourner" },
    { set: "M19", name: "Vivien Reid" },
    { set: "M19", name: "Vivien of the Arkbow" },
    { set: "SNC", name: "Vivien on the Hunt" },
    { set: "M20", name: "Vivien, Arkbow Ranger" },
    { set: "IKO", name: "Vivien, Monsters' Advocate" },
    { set: "ONE", name: "Vraska, Betrayal's Sting" },
    { set: "GRN", name: "Vraska, Golgari Queen" },
    { set: "GRN", name: "Vraska, Regal Gorgon" },
    { set: "XLN", name: "Vraska, Relic Seaker" },
    { set: "RIX", name: "Vraska, Scheming Gorgon" },
    { set: "BBD", name: "Will Kenrith" },
    { set: "MOM", name: "Wrenn and Realmbreaker" },
    { set: "MID", name: "Wrenn and Seven" },
    { set: "MH2", name: "Wrenn and Six" },
    { set: "AFR", name: "Zariel, Archduke of Avernus" },
  ];
});
